[default]
[default.variables]
os = "linux"

[mac]
depends = ["linux"]

[linux]
depends = ["shell", "zsh", "nvim", "cl", "intellij"]

[shell.files]
"git/.gitconfig" = { target = "~/.gitconfig", type = "template" }

[zsh]
depends = ["shell"]

[zsh.files]
"zsh/.zshenv" = "~/.zshenv"
"zsh/.zshrc" = "~/.zshrc"
"zsh/plugins" = "~/.zsh/plugins"

[nvim.files]
nvim = "~/.config/nvim"

[cl.files]
cl = "~/.config/cl"

# this may not work correctly in WSL 
[intellij.files]
"intellij/.ideavimrc" = "~/.ideavimrc"
