name: Install and Run cript

on: push
 
env:
  CI: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_ENV_HINTS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

jobs:
  install-and-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install and Run
        run: |
          chmod +x install.sh
          ./install.sh
        working-directory: ${{ github.workspace }}
