name: JSON Linting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install jq
        run: |
          apt-get update
          apt-get install jq -y
      - name: Lint JSON files
        run: >-
          find .
          -name '*.json' -print0
          | xargs -0 -n1 jq empty
