name: ShellCheck Linting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ShellCheck
        run: |
          sudo apt-get update
          sudo apt-get install shellcheck -y
      - name: Lint Shell Scripts
        run: >-
          find .
          -name '*.sh' -not -path './.dotter/*' -print0
          | xargs -0 shellcheck
